<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="5" total="6" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="10643" started-at="2020-11-12T18:43:41Z" finished-at="2020-11-12T18:43:52Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="10643" started-at="2020-11-12T18:43:41Z" finished-at="2020-11-12T18:43:52Z">
      <class name="restAPITesting.restAssuredTest.basicTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:restAPITesting.restAssuredTest.basicTest@6a2f6f80]" name="setUp" is-config="true" duration-ms="11" started-at="2020-11-12T20:43:41Z" finished-at="2020-11-12T20:43:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="getPetAsync()[pri:0, instance:restAPITesting.restAssuredTest.basicTest@6a2f6f80]" name="getPetAsync" duration-ms="10613" started-at="2020-11-12T20:43:41Z" finished-at="2020-11-12T20:43:52Z">
          <exception class="org.awaitility.core.ConditionTimeoutException">
            <message>
              <![CDATA[Condition with lambda expression in restAPITesting.restAssuredTest.basicTest was not fulfilled within 10 seconds.]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.awaitility.core.ConditionTimeoutException: Condition with lambda expression in restAPITesting.restAssuredTest.basicTest was not fulfilled within 10 seconds.at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:136)at org.awaitility.core.CallableCondition.await(CallableCondition.java:79)at org.awaitility.core.CallableCondition.await(CallableCondition.java:27)at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:840)at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:802)at restAPITesting.restAssuredTest.basicTest.getPetAsync(basicTest.java:193)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- org.awaitility.core.ConditionTimeoutException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getPetAsync -->
      </class> <!-- restAPITesting.restAssuredTest.basicTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
